### ISSUE TITLE
Pasirenkam darbui sekcijas

### ISSUE THREAD

**Issue by Algis1978** [front-end-by-rimantas/30-grupe-portfolio-docland#2]
Projekto suskirstymas sekcijomis čia:
https://algis1978.github.io/Bendras-projektas/
Jei tinka, rašom, kas ką pasirenka. Galim čia žemiau.

**Comment by belauzas** [comment]
Ativaizdžiai nebuvo klausoma, kaip yra dirbama. Susirašom užduotis ir tada visi viską ima iš eilės ir daro.

**Comment by belauzas** [comment]
Pabandykit nueiti į darbovietę ir ten tokius bajerius pasakyti, jog darysite tik tai ką norite... Iš kart gausit nuorodą pirštu kur yra durys :D
