### ISSUE TITLE
Button

### ISSUE THREAD

**Issue by RimantasZiedelis** [front-end-by-rimantas/30-grupe-portfolio-docland#26]
- [x]   - button 1 (changes color from light blue to orange)
- [x]  - button 2 (changes color from orange to light blue)
- [x]  - button 3 (changes color from white to orange)
- [x]  - button-play (play video button)
- [x]  - button-up (back to the top button)
- [x]  - button-arrows (carousel buttons)

**Comment by Algis1978** [comment]
Viso puslapyje panaudoti 3 mygtukai:
1. Hoverinant pereina iš mėlynos į geltoną ir atgal su rudos tarpu.
2. Hoverinat pereina iš geltonos į mėlyną su rudos tarpu.
3. Hoverinant pereina iš baltos į geltoną ir atgal.
Pozicijos:.
1. du mygtukai: header ir student review skiltyse.
2. du mygtukai: pricing ir learn UX design skiltyse.
3. vienas mygtukas: pricing skiltyje.
Uždėti pavadinimai mygtukams:
1 button12
2. button21
3. buttonwhite2
